export const FETCH_STUDENT_LIST = "FETCH_STUDENT_LIST";
export const FETCH_STUDENT_LIST_SUCCESS = "FETCH_STUDENT_LIST_SUCCESS";
export const FETCH_STUDENT_LIST_FAILED = "FETCH_STUDENT_LIST_FAILED";

export const FETCH_QUESTION_LIST = "FETCH_QUESTION_LIST";
export const FETCH_QUESTION_LIST_SUCCESS = "FETCH_QUESTION_LIST_SUCCESS";
export const FETCH_QUESTION_LIST_FAILED = "FETCH_QUESTION_LIST_FAILED";